#ENC[AES256_GCM,data:GvWmpwgDc0CDwQcyE02gSdf/VYLLZf7CxWbBH7jCGLzHjJ3txR9LjkG3c9YHZW8ioimHafkI50E+qD0XfJF6bqRxGPk+LMTUs9ehOQ8x,iv:BcGcZjPQD9YVdup8hIfUHB2QHyEVp8EUyJwWGRrURh0=,tag:+9+iz2OzgLZ7aJpRVFHj3A==,type:comment]
#ENC[AES256_GCM,data:dDTufnbGo3+Y3JIJQqZeYwLLPfxjCVqRyTXVVePTaq+vCB3Z,iv:Hp5sBEePc4WFe7SXYthZHZ/cj7bPTTGVefxlUcPtsfI=,tag:EMtViEdk1Ls+A4Ex5wm4iA==,type:comment]
#ENC[AES256_GCM,data:GvWmpwgDc0CDwQcyE02gSdf/VYLLZf7CxWbBH7jCGLzHjJ3txR9LjkG3c9YHZW8ioimHafkI50E+qD0XfJF6bqRxGPk+LMTUs9ehOQ8x,iv:BcGcZjPQD9YVdup8hIfUHB2QHyEVp8EUyJwWGRrURh0=,tag:+9+iz2OzgLZ7aJpRVFHj3A==,type:comment]
#ENC[AES256_GCM,data:jFEScvJDPT90VfmJJ9sX73uDCDTxp6nTpoeiRg==,iv:cIRslarhRZmkPmAK3dG8Jw9nNbV0nIwQ0mkyg4Wosg8=,tag:MpNgh/VEdhq4uh3CoFjSFA==,type:comment]
#ENC[AES256_GCM,data:JV3ukDZUgpiEgM+u2gYtSJ5BjdwbgXNLHJwmSzbKJmXwf9EJcpY2628umAIEJfosvGjQyBWZLq0h7Xp+,iv:QCdDErehmw2tIAHrLds3X1wnay0n4V5FtOkVde4Iq1o=,tag:Q2JvabJzHq7yrkvFvUlz4A==,type:comment]
#ENC[AES256_GCM,data:BYCQUBN4rWq9Lbqnx7i4BAdBj3x/wYybLDwYAdRq/SJ9Vpxbb4xDe2miU1EuKw==,iv:t1VyhFabNfKVlVbYFHqJI+KW1214XBt+2fvQ8bfnoI0=,tag:uzeMLdsVGUGzN9I1CZWClA==,type:comment]
#ENC[AES256_GCM,data:i0H4n+JHz8fL5bZBdgi/q7tQk1vUu03zWgwviGIrql8D/vIV2waPba7MVxHizOVht0VNaQ3o,iv:MMeBtZEO+N6BwnUJxml7hQ3JqAgv+2Z5O4P5WFM+KzM=,tag:qz+rjKkb8I8TFvVT5Pa7hQ==,type:comment]
#ENC[AES256_GCM,data:tBkMv2OlVxJoQnTtr4gba1V0G5Gqs6YjrGaQNIJgyvX/AmpjkVSqxtXVso+CWo9YldoNJEYkuyGeZw4l9ERYFS+DmlA/xZFwDcYFgqQY,iv:NGzkzB0cB8SMY8Ldqz7qGuDL2OiHsGLJ1qJlEFbGKE0=,tag:2r2Gg0RV1U1l1VzfFECcXg==,type:comment]
#ENC[AES256_GCM,data:X/MuHzk7oZ/AwrAbVi4x615sVn5N2o0L/l0vBkQ=,iv:fyFbxunlf4IKMUayNs1/BfZTvhqkSHoeoZffw8/bq9c=,tag:ywl3JWkBD6Bjp0v5LNfe0w==,type:comment]
#
#ENC[AES256_GCM,data:LtGWAIdj7jx0OSPg0dRefJPeZD38bLC2YX8o3BcfDpXD+jwbkUvhxvwWf26i3QN4T8fImZUL,iv:Olq3Tcg58iukIjDht67X67foUwTbpP4BMw/dM86P1gc=,tag:F/Qu9TwUCxio2KoHBiAWVw==,type:comment]
#ENC[AES256_GCM,data:GvWmpwgDc0CDwQcyE02gSdf/VYLLZf7CxWbBH7jCGLzHjJ3txR9LjkG3c9YHZW8ioimHafkI50E+qD0XfJF6bqRxGPk+LMTUs9ehOQ8x,iv:BcGcZjPQD9YVdup8hIfUHB2QHyEVp8EUyJwWGRrURh0=,tag:+9+iz2OzgLZ7aJpRVFHj3A==,type:comment]
#ENC[AES256_GCM,data:7ScWYDMgCV7u0qSNRuqq6o2+7h5ypi7Xzuzq8FtsC3ivOIirBXkpCQ==,iv:xYgQ5oFTjc0/0+Tx/dlIb1XPvhIfwhro+9mVORr6xPI=,tag:SXAIyJqQ6J3CKl4zbtVX/A==,type:comment]
govc_url: ENC[AES256_GCM,data:+0iZ7tqQNIhVJ3fWOKnjep0=,iv:Yy9v7ZK8ye9fvSk8sri4VTgkC6R5SyP0GWEn5Or3rG8=,tag:kf2A/f686n3T+7BIfIaG2w==,type:str]
#ENC[AES256_GCM,data:tNmtwc3yn6rTANXsQXyER5aw6WmOMP7qlkYz97lDDjlyEU8gp8ElTwyA97yHlWzL4zgzFblnh5Py,iv:LSp6+JW4Ohef6pWGi+Nuk/RNSr29oTr5z0NjIEJU1gE=,tag:xmSnT5auldqMk2ElP/d+5A==,type:comment]
govc_username: ENC[AES256_GCM,data:kuG7CXpem/NgvW0TW3lsUg==,iv:wMNUZT8zzShuirh2fhUq3MZTPooKGAyMRN13vyQfdtc=,tag:XTvbtV20XVVbXbRvQ3/RdQ==,type:str]
#ENC[AES256_GCM,data:Yb857Gn+KAa0hMJQt5Ft1B8=,iv:345LECCoNI1+XHGRuCFi82nKGnSfkEC9RAW5OD6YI7U=,tag:wlDXPwop9X0LNWDTyA9m7w==,type:comment]
govc_password: ENC[AES256_GCM,data:aqNb4VhMz0wQW581lIv33AK5,iv:oje68E/5mmMOrkqp3B2lTJKq1IxPlKN8PRSEwX9RFi0=,tag:dwNpEewU7ySRBRNJhtg3rA==,type:str]
#ENC[AES256_GCM,data:ULQYaf+t27ZsjRvmLixFCon2bqVl78gvmHgNPQgDD3TLq5zefx9lE8EfRBagcpz0nEBftnvDu/rShiw=,iv:8CeB9G/PxTkjwKH1ZH+9LV0bLQeuaSjlV+BsKJG3poc=,tag:SZ9TOC0Hw4S0rxKjEu3f+w==,type:comment]
govc_insecure: ENC[AES256_GCM,data:B3XWbQ==,iv:xfctdbpBHjqDS1eAtpiSjFzp6vGJXAM1OM3IFVo8fWU=,tag:HTYZNuINIE+F1QeIgaWvUA==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZzBQd1k1Z2RsdzV3UnhI
            NTE2bC9jNXp0TnpCSnN3Qzlxbyt2aVFoYWxVCkNzMElEbDBCOHd4RVdTMklEVEdP
            czg3Rzhib1BBRUJFTzIvbDhzc2VzNm8KLS0tIEczOHpnazhsMG9FYjJLdmtJU0Zr
            Y2xkR3JNRUhQVWJRVk1kSHdkc0hyc3cKMRdujTfefGsUaVV2roKGTTQbc+ykfwy/
            Wvt4A47slRzJcjGvT5ad8ouBg96tkz60GdV3po2awbKnZ8P5lxtWWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T14:17:01Z"
    mac: ENC[AES256_GCM,data:dvC6F6RXvDwRISPlcN5zIomG9jP/4bmYpVMipQBmB5xF3U+z6wUXwdw2EtqHNkTO9xHo6cehn5dbu1QMOxubm37t6tWZPQXflENGy/DbcQAKLAkAH5wnC8OuFLUIrXANMBv0nf0nmHm/SEYWCfPGHmIQIn0QkPxajKitXrmRUqc=,iv:TCaUlG+VdGOFHiF9Hf0VaqQjp8OxH0x2V1NB+CFMeZM=,tag:04uW/d9v1yCnmnKKoij7PQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
