govc_url: ENC[AES256_GCM,data:ObY5TMc1XnE/6CHro18YpDE=,iv:TMv3vjlkxfbuEKNkhtgtMez/4Mmizp2A3GVwxhAzhrk=,tag:uKO5x0f4vrTXF/53Mxzw0Q==,type:str]
govc_datacenter: ENC[AES256_GCM,data:5Au4wnfjO9FzlURO,iv:5j8ZsOXdDYnWb1bhFNtAWzeACjOypPFkXv271GpEkfY=,tag:mC4EbDoVasEMv+8CNEOpeQ==,type:str]
govc_username: ENC[AES256_GCM,data:ao7ypcMT8DVhbSL4u13Gsw==,iv:GNFPgw5nu62SxE8fjpt6AXGHBDrJtwEjruGFjMmpy8k=,tag:E1JGCIJdU88hEz6WCs09ZQ==,type:str]
govc_password: ENC[AES256_GCM,data:Mfu2kb2gNrKxQhaqJzHTMEg0,iv:fftdr/u/VsVZ8LyADiLd6ZESL+jmyeBGH86jaZdiT+I=,tag:z65/78jaxfDYYLN3qKy1mQ==,type:str]
govc_insecure: ENC[AES256_GCM,data:a6htlg==,iv:ur/WDRptDZyv5kfrFPR4Nm860qem6csRfpGXHrglCA4=,tag:bqFYMAi/JkWHlc9bgYCYiw==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVnVOc3J1dVJQWEZ4enE4
            UlpjK0cvbThkWk81ZnNKSURxeEpnZkdLcHpVCjlYWXlYNzU0KzR1b1F4UXRZZGZu
            YlZKTXlYdjc5QjhPTWhjS2ZJQ2dlV2sKLS0tIENLMHRqbFdnNHNuTGQ0RStNa2ZN
            YUN3UWh3SHdVUktlMVhNWmNVaktwN3MKvY18JFim8JE2bByOYyCgBnq7AvQl8/0E
            lHhq5kjE97XBFjrlsWfC+F+QgedcpSzxLbHQd1LroTrg8uF9eReZgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T11:04:32Z"
    mac: ENC[AES256_GCM,data:NpjfwmgTWTljvIklb9uTOYZeCCvnkaHK8aM18YoP0sxGpE4lANdvvnBm2XJtMXqJOB56U7Q99J2I3U4s1RlmeekTlLlolqp+orgityXTD8P4S/7QoNtYHJaQ+4h45/4zEADsDvNo+VGrE8Nf4DEdbVSF9EyrCkT+1ub0OWQI190=,iv:+xScdNEl2+bgEEiM7QQUOxMK6+774Nt9lAb/U5wIiDY=,tag:zwGiptpm8Mby6XdXU+uygQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
