govc_url: ENC[AES256_GCM,data:vMjX/hDaPjtdOpCX+Jn1+Sw=,iv:hKRiQx0lY3tO1NwzqKQaqllKelsWIc4DOl2xRyrvO74=,tag:B3zD6lGKV4s+DQqNuTtiJA==,type:str]
govc_datacenter: ENC[AES256_GCM,data:MAVzjv4+Eu1UvVnI,iv:buusCPkKIExF9WA6mdpIZsHaXnMCuZ7n+j5ZeHd8ylE=,tag:p+xtV75X1pXS8HKRJhztAQ==,type:str]
govc_username: ENC[AES256_GCM,data:pkb7zjbSTs81Qby7ocoRAQ==,iv:bku3gPLAzKyHfLT/zci9lp7UWS/fLrDQ3vmh7z1qmBs=,tag:2DJ6nOH4Ys7CZyMsT08yGw==,type:str]
govc_password: ENC[AES256_GCM,data:o2OPMeFEuQlZQNa7KNafHWKa,iv:8MW5ihhfl9vqSJS/TAx05Iq03brLD7d4rjtkLwtdQO0=,tag:2mynnyWStdrYNHhdvrJdMw==,type:str]
govc_insecure: ENC[AES256_GCM,data:AUXxFA==,iv:Y/2e0f+WHy669zwb8gcvZ3TSpqDJmslWn3AIhjLZY6w=,tag:IGcnuBLDIosUhAOLuLrCJw==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcmpVb2J5dlo0ZlJmejc1
            RzZLa29IOGhCK0FVVENRT3VMY01KUnlEWm5rCkdtNHF4cUdmSzFrU05pUlZzVmd4
            M1cxbFNGQ2o4bnE1L0ZuZFMvOFd5VE0KLS0tIGtXODl4dWhIdU00Q2x1Q0N5dDhM
            YTd3ekY2N2RvWDdRVlM1U2NVcE5PT00Ku3e7MTuh/4kEqh2XnNaIX7g7TW/4GIx9
            v+ZxKrrl1qb0q48lJ8YIdwPLjvt6JQJfOtN8lM4IMkEPBsgl9BuJAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T11:04:32Z"
    mac: ENC[AES256_GCM,data:XnM1OhrR5pxjfNl//VrKN/QtSLcBNvNtB9HyKCaYdrdC69dE2MhI8NAjcK1Gkoq+Hi7T6HShHf70qUwsborBGLUhspc8gSfW2cdB4ffo1R6bL79lcR8JE+L0rtMHGYZPKFhWTIeJpj/NOJx8ZNr7/9o/rrfqaaTLVqMmonCzzdQ=,iv:2XQ8xd9srRjrzoLC/vWV+mjL+NMU9H3NBdn1yWgtMHw=,tag:JhTEJ1oCoRt8qbqx82k+DA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
