govc_url: ENC[AES256_GCM,data:R6mga3mms6IQZXtn3+kviJ4=,iv:b7DO6Cv0yZRIyJGNwq9iqQT37FzdV5e0i3AFWfC9ICo=,tag:rD4fqzB5+7Blf42etfavNA==,type:str]
govc_datacenter: ENC[AES256_GCM,data:s3a/SIZJ4uRx5TOsXOFo,iv:R+sonnytYmp0ACa+OQM5B4b1JB5lh6qc9t7ImUb1hGo=,tag:VLdyeoGsYZGk/28LlNXz6g==,type:str]
govc_username: ENC[AES256_GCM,data:yzjRPUwzNqWduoPqvAXBZQ==,iv:2eGVLmCY/VPwShpfffKIvfey1Rndssk++Qf+p0LRF/Y=,tag:RdrKSOzQ91J7BVAmgYJvug==,type:str]
govc_password: ENC[AES256_GCM,data:ycw8t/LIxGhHDGLLzN8XYw19,iv:dKo4NAFCO+JBMwXq054O0LqvlNoY2FT4Mx7Jib955E4=,tag:b/kTZLMK5MDn9jQn5UxL8Q==,type:str]
govc_insecure: ENC[AES256_GCM,data:GnlIPw==,iv:IGWvSXmDVgDOVAPQM/4MOymDSJzm+OREvYrdKvOkQvg=,tag:ybfiVAj9D80yP5FXqBFN8A==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WU90aTlJVHVISXZ3dWtL
            VzJRMjFudW5oWTg2TjdlcjFpUWlTb1huK1dzCkNQNFBkMWFiTkg2b3BxMXhHUzhK
            a2MyVXpkQVFKejJpSXVaMmtaRmdmOE0KLS0tIFpHcytKNHc2aHJwSkJBVUxjQ05T
            dFhOUHRrQ05qRzdiTUhXZnYyL2FucjQKI2OAw1hvTonKu5S44ateBN6CpS+ni7Rj
            X4Q4xEqLdVIaMHSzuVxoWavunAUxwg1GjzPk5systDFjU9gsatdpKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T11:04:32Z"
    mac: ENC[AES256_GCM,data:LAGOHvdUEzF+wt6pwDHjTB74rZInHJupZmIB3vSJ7EhaF8WVzu747sED48Fbtpsr3pwJppgQMt19zOU0lv6CAu1U4L0PiJ2k9vaAGnQc7B+w/05VLmy/Hsee8LrPs9lmBRUCLp8BkosV/0TXK9ldk+4uIgN01PNBYIBa23HepFw=,iv:iotikLtTkOCgx9IdaDnLK1QMqCtSthd8olbNnW5B5pA=,tag:y3RXubfuhQh6JwYo1huEjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
