apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: monitoring
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:kfLSHxrjd49ZDVxmh5a9oPy3AxO2ARm7Q8ceI6ssMME=,iv:TEzdaBajZeLrDhZK9hgwgFkXiohBq6Vo36m7QMtIAmw=,tag:4v67LWHtsULB9sX/aFyIOw==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:nJpuDv7euDYLSJ+CD2jZre6fZh1s7vYWy6aHP13/E3A=,iv:Fz6QLu0j1LWU2JIh5sX0wZPjmZR5uwDrYU7qEOIXLwo=,tag:esi2eELbzoYJtv4JTf09Yg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZlBoM2FGK1plaXB5djZK
            d3VxMWVQRUtHc05HYUprL3NvTmFxYnR6WDFjCmc1RXJvR05pRmlVKzNRMU5kMTBv
            NE9YSDZXUlJmSUNzaDBuUkVEcXd3eUkKLS0tIDV6MFhGbWx0R3RQVjhWQzNoZ0o4
            VmlZT291cXdpYlgwMldYVXU4aUlEMzQKIv0b67OcwlTBHTWgL9/532sowlqyjmj+
            0aE/j3unbaqMEdfOL8fwmBPZWB52fPla6+TI8HsyeitzJINv6qwHSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T11:40:10Z"
    mac: ENC[AES256_GCM,data:SqZqbs8MZZUyGTKikNzbuXJY/1AipY33zyGIrA7QBA481mcTrW9kscZNSFHxREmpdBE5CJ0O3yWJAIO649OyAB36ox0SEI2xrkMp2pAfb4cI2ZZV7i+KaSx3Vc6GDfVt8Be7wwxkx7Mk/oDzwYfeGCItnhaCb81VlsegOmaKP3E=,iv:LHCd4osVdHzci1qDCIKGbyPpuMsZqGo4qxTnFlDNhpU=,tag:bmTui7IebImvgTwMBtVuXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
