apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: monitoring
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:RwLYGKDKiwvPvcmH7ZfQEnpiUON3h07Kx3s/CoLOdLI=,iv:e77JR8XG65iP0Iph6sop5A0OweQhLOGSMEkPpcSMmdA=,tag:RbABOwGtWDTwiTPgkxzuww==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:KaH+Vqql0EMGvty711x7TwWpWtIH3DCrnKGbQcQzvgw=,iv:s0KrJeEks3lT7MJMaxoQRFie9UoGybL/7laCp29ATQo=,tag:Hikg4EojG70MJhlwAqnnUA==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHT3ZudkZQcy8xa2NaRjRt
            QjVxcE5HNVJYcEdnc1QrbzdoZFRUc09CdmpRCjdPQlBlNkFtdTZjM2NYYkhqVHY1
            cmRqSE95T1ZSdDJsVVB1MU4rRHVYM1kKLS0tIFdSQ3c5RGdFMGxPSmF0cWMrM05C
            Mm1rNW0wMlJwV0VJY1BndzJYbG8yZTQK7xZkgapRnFUDen4p5YeSdRkaaQfLOZaC
            12wvV724mVB9eMb5fWanlV0oBxMGI/0DoIl9C5gGmGoCuFMofTrcCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:56:30Z"
    mac: ENC[AES256_GCM,data:AlsS7YnlcGiVhg9rpV61lTmlS+N3u7QztnnPgwhU97PO9CZL0VyMjXYjO2J8uMRPxp1wHvKh17nJDvzW//j1nSbjl8bqKNZ1V9nC4eukFi0NY5XqYIHGAGSF2wM4ACLcI6pVQ4KkCSCp+d7t7LUNJjOesQlSPGzHK8uNhqLlvKs=,iv:D+hthELU3ByqdHX9PFtDSKIn3650s2SNnzaz1XB1W/c=,tag:bVVIdLAe98EmV1EfaJYyhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
