apiVersion: v1
kind: Secret
metadata:
    name: gitea-db-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wcVRyHs=,iv:KidiEJ25r53ETeFPPk8at2/WQ6GzH1srvOAiWZZhIVo=,tag:o0puOG+CehxVvNNxF6d1wQ==,type:str]
    password: ENC[AES256_GCM,data:f6sc/HOSJBaSJ7ErplGYvd6YWrl48YBqTB3Wu9KU14U=,iv:eQtlIGa2CUMI7VmxOfiMsogTBXhMr11KxaQEnlESQ6A=,tag:kE6ncrbvfCPUl95jIs9aVw==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d2ZxSGpOZjMvVGRDMlk1
            NjF4MmRoNWc2d2cvM2RsNHB6bWdXL21tU2tzCktOSzFacHAzdVMvUmpmN0lBVkpP
            TXpZM2svSkFLbkVGUGVBbEgwY2JSKzQKLS0tIEF4YktKZW1HcnRiUnRLTnZyMk5F
            akcrbVZmZFM3dmtmWnNuMStHVXNGSkEKJKGHkBupp3+LXTZ0ScY/inUiHQLw4Ny8
            tweFe2AU4FWPyJ1fixwgQFl1fPUcc6ryb3qO/3QqYGuTdCppZrp9PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T12:54:32Z"
    mac: ENC[AES256_GCM,data:i5EBbcm0vY16l1sIUmAnAkRNia1ZEKNSViYTepSgTEOSyy58T722MumklVat3nngkpOJLy7Dyv7n9pt2gq+qH2TMDlzLTXHjSRDbN2ULKOAy3sYTUt12epvg73tF2KAB+mgBB1UrSMVh9zF7ktWgVlFS/IEGROT7DJ/F2H/i2Hs=,iv:bUyGZLkX/py2RswK04yVDC1JuNfZIHfwtOzieKknEZQ=,tag:cJfEPYkD6j467wEBeVxvxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
