apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:PP1vJqjvQWE=,iv:vwjhnMVbTtQjS6GUqBVeculSg7BVpkRtvWVz+uyk8OU=,tag:fghcxSU7YvlLMDyt2Qysig==,type:str]
    password: ENC[AES256_GCM,data:afLb23wIx6jAE98fTgOUyoHa9kyKD+xo41zPKbN2AvuvAeh2TyYVz1WUETcFbE3K,iv:C+IL3/z/mqDzaRRcZ7Et+M1yBIkxa69AZBJB1+lI//k=,tag:QNSmcZUC4AgMNXhPtfWZSQ==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ0dTc1VKdVQ1WnJNNnpE
            RExnM2xVOVZVOE5XVU5IYmZnODhDUWxzdjJnCkNpajJLUnQwVktMMURvSXJ6NVZR
            RWZ0cEtOYUlNTzB5dHFveENHcFFrUGsKLS0tIEZtR3g2bEZEZUxiNkpGQ0Z3dWxj
            YVJmaGZ3bEtRUndsM2hlaWNEcW45OUEKs4oQBNuCUHpNUpgoYLKrquQEx6DXZb60
            rmqduV0jlUGits+APu9CLBZE6PYBZaPVjEnB2uTUBO3XPfLv0Mu8xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T15:31:16Z"
    mac: ENC[AES256_GCM,data:pOiIdA0sMrJ7ciJi51JZGTM5FUEATSapMKajXMzjBO/PPivRZcE+8+bj7+up+I19V+EulPEhE6xCPy03RKLiV6vCErZH2wI3MciJFmgKKa7VUEk00uBPDnFaioiF9YCi7kA41gSIwkFrae6fCnwGs3cJMq21jimyHL+GxUIC4Vw=,iv:OY4akKjN/FBoZt8z0VpIHUftifekmejmkVkD8jpWAWk=,tag:DCChu6ExpyZMVFBobo0Pow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
