---
# ArgoCD Application: Grafana Ingress (DEV)
# Certificate + IngressRoute fuer grafana-dev-v2.eneg.de
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:dhenkeeneg/eneg-k8s-infrastructure-v2.git
    targetRevision: main
    path: kubernetes/environments/dev/monitoring-ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
