apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secrets
    namespace: keycloak
    labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:2+NPw7Qq5VFNZoU6cnlm0D2U9Ah0b5L0gEhg4rQnscrYdU7EhPO/02BMcGBFXiX/,iv:khD0Ms6HCSALdnnmECyVHGqO0A+Mip2f0Ael9vZsNsM=,tag:X0xWIJR0SLd5coI2//hooA==,type:str]
    admin-password: ENC[AES256_GCM,data:b/x2TpmT39vy9pPDfvTd35NGEuynnt6NsHCoTUM0n0Wb5bgrdaqF9+8YnV1VY2l9,iv:80Lmu7n73P3fcOXVDe8a2ZZXE6lxJVI5frXmOe4aWrc=,tag:dmVb/q/HG7sW/uTfsOPT2A==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdzY0OVQ1M05RYVJSb0xU
            OGE4N3NENEZOOStaOWdmMm9sSmRvUUxOUG1nCnQ1Mm83cUNxK3VYMGhhaEozenk2
            R1daZGk0UmhMcVRlRTdZTldyZEFkRU0KLS0tIFdSZU9IVVN2SFBUQW95WnpoemRo
            ZjU5SGhXa3dTNXJ4amR1VWdSZlJrcVkKZRzCKxd2nwbF6CDKZMz8nDht4MuZL633
            SGDOk2UEOIHaqs2H6mX9IkZv8P6Ajs29/YW2DApNnvq5ZXoBd4dJwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T15:32:03Z"
    mac: ENC[AES256_GCM,data:V5TfnO+rvE8gxbbqQz7qFyCG60vccnkig4PdomiW2TxhUNfA8tdq5MhyF2/ZlDnh62kgv81pxH0yo+1uaHSd3RKb6M7r5uFynX8zoUDVRp8HL+H4VJl85JRESjp/oRkHFP5i8HAXgOOeJ32tWutdL3SoA/65DaO6YUmgBj0iKZ8=,iv:tVu1Z9Ib9XaG1u5Y6iGkgbcxaQpOt9WINPKMykNKaKg=,tag:1cwS6aR9fVQ5yM4Yo4tM+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
