---
# KSOPS Secret Generator fuer OpenProject Secrets
# Enthaelt: SECRET_KEY_BASE, Hocuspocus Secret, DATABASE_URL, S3-Credentials
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: openproject-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./openproject-secrets.enc.yaml
