# SOPS Configuration f端r Age-Verschl端sselung
# https://github.com/getsops/sops

creation_rules:
  # Regel 1: Alle Secrets in kubernetes/ verschl端sseln
  - path_regex: kubernetes/.*/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm

  # Regel 2: Alle .enc.yaml Dateien verschl端sseln
  - path_regex: .*\.enc\.yaml$
    encrypted_regex: ^(data|stringData|spec)$
    age: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm

  # Regel 3: Terraform/Ansible Credentials
  - path_regex: (terraform|ansible)/.*credentials.*\.yaml$
    age: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
