---
# KSOPS Secret Generator fuer MariaDB S3-Credentials + Root-Passwort
# ArgoCD entschluesselt dieses Secret automatisch via KSOPS + Age
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: mariadb-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./mariadb-credentials.enc.yaml
  - ./idoit-db-credentials.enc.yaml
