---
# KSOPS Secret Generator fuer Odoo Secrets
# Enthaelt: DB-Passwort (Kopie) + Admin-Passwort
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: odoo-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./odoo-secrets.enc.yaml
