---
# MetalLB L2 Advertisement für PROD-Umgebung
# Gibt die IPs aus dem Pool per ARP im lokalen Netzwerk bekannt
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: prod-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - prod-pool
