apiVersion: v1
kind: Secret
metadata:
    name: garage-secrets
    namespace: garage
    labels:
        app.kubernetes.io/name: garage
        app.kubernetes.io/part-of: infrastructure
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    rpc-secret: ENC[AES256_GCM,data:5LM8dM1Eo5KO+tYdUV08Rn30Qsv/XIwUpBtjCo5aS/RQJhIzP2ThFiDjbjEHgyl64KWyUd6nJ+1x5ngaRIZKYg==,iv:ivhoA2eX0v/iY911Yytmmb4nAATPShlkFv3yvu7fhxI=,tag:X9lqNxzIhPwRuyid8NAxjA==,type:str]
    admin-token: ENC[AES256_GCM,data:E0js/NHYEeq9vtWLx/yq3/WnQrZTLNkVRhLQD9WsEqTxWU/Fp9SINi4wH5upoBotrKf4Nj5HUpKAG877YrHhOQ==,iv:Qo6KfL1uYXmaTpVHlkDkQdFsghYCv3bRQl4V5ZyWXLw=,tag:e6RFiXVAdFGe9RymI7e6fw==,type:str]
    metrics-token: ENC[AES256_GCM,data:PuKzcaCZ0zGJHNzYhwtbkBP5y7uAjfHomPqOtHjlPboo01oDIdZ9lLLag4/m0hMCqxIjYE3jHFRaXtj6bA2zww==,iv:r77QDaT13DZCL5eEfSxiplV/u/Mgzk5FAWDOsf99+LY=,tag:bloBgcIOuFvLI2oEx8nxUA==,type:str]
    webui-auth: ENC[AES256_GCM,data:79zC4kVIl0DMCKng5doqsEdA1/JShCwacVSyQeWr9KvC2UlfZqcB+LtZ9kz9P1qwpGmFnLYlgPOrslXDeoOMweRf,iv:SR54p7q1lyNeLfdkqpHmDz4qJbxiqb36Vf5huL6fCt0=,tag:on3RgomBRtPwgXEGTvoiAg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyKzVMc3M5ak1TVXA3d1BL
            emplSUpLOFhKcnVEUERmcXdCRzV0ZzIySkFzCndMT1lnR1dybUpRdVFlZHBOUVJP
            SjlzbmpJZDU2YjJoSm5PZCtOYjVLRmMKLS0tIFd5aDNVZVNscERYenZKS0FIeW5Q
            VUpPcmMxODBUMnZZMk5ZNWJjd1lVN2cKi1h0PW4HLsXXsHJX4gpwmyGgUl2+EjWh
            IGtToUfi5MYLF4lmGbTPwVNzLejxhLzsGuFV3LZ6kd93qjQ/mi6X0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:36:59Z"
    mac: ENC[AES256_GCM,data:eCzvys1XgJgkzvEdw5pjxGBETItF3tEIWdvPj3uevm4OKCd5h8zwgogFUVjs7m80g1izGHjkenL0haQnQktfUFpHQY1zRplBXxZqvt4IZsNpa+Cc5jRZgIy5HdyDmERoJ84UqSuSh0RPQmXnEY+4umer4ItJHXfN6t4ZspmQur8=,iv:npvyJYESbA/ZpkiXbwFTGLC7p920Ar9rLJPUbPm3O2M=,tag:i0vQbfErI6CLjtzWRYBmXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
