apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Traefik Dashboard Certificate für PROD
# (Helm Values werden separat ueber ArgoCD Multi-Source referenziert)
resources:
  - certificate.yaml
