apiVersion: v1
kind: Secret
metadata:
    name: idoit-secrets
    namespace: idoit
    labels:
        app.kubernetes.io/name: idoit
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:IHVsvJQzdsPl71R9I0cNC3FkcEH9YLFRqptBmNRuG9H0aCY2MDU2PnRigm/J9SZJ,iv:hjtht7MgFNcDa9NNU6muU2mGXKbk/HJ83YYrDN0uXuo=,tag:cKeGo/Djq0jGr032VWoB5w==,type:str]
    admin-password: ENC[AES256_GCM,data:OS+cSXVlhf93NTt9Q+PEqwq0MeissJwKTy06XC4Y2zU=,iv:6rNxK/Accaz5v9xVrWt3RNdOrA9Dn1wpgl0x2OmXYkM=,tag:t+COC11Z7jwWo1hJyVaXJw==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM0x6VmdPVlBKNW9tRmI1
            WUpmdHFnU2hpSmduQ2JUb05Ud1VSOHVBKzJjCkljbW5tSXNxMGVlb1JOaTVtREIz
            TFlESWdub0ozWG01eXltd1BTUmxVVGsKLS0tIHVLemtKOWlMTWhoU1l2QkoxMXg4
            RzE2MldmTFVFcDNKYjAvUDQ3YzdrbWsK8Ixo5qmFmJaN5HTGE1d/Pp7V9IPPJclC
            QNf8e+1/vTNE/NNzyVoB8VL9vceDgbH0Mvj6R+qqnQtJbDxaGuT8gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:46:06Z"
    mac: ENC[AES256_GCM,data:1lVNcJRMAxlxMWZUws/KLSYkKYcfZ6zxkVu3bRrXGM7ua2krU1yeaYGZr1Uhx5BaEIQWV/H43EKNj6UyOr61htDgxI8eAZLmmIn7JqQz8dFDJQaADlOXNJzxM9YNn2t7FbIVfOgqzOcEwGN5iwNVZ/qzSm2kHASBXKLcLvJv69A=,iv:zi5CtEYk48n4S3ku3FoiWWOZ/uwXsl77Y718EAY2as4=,tag:ZK0SgXr48J6O0MoCm5j2BA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
