apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Basis: MetalLB Installation
resources:
  - ../../../base/metallb
  # DEV-spezifische Konfiguration
  - ipaddresspool.yaml
  - l2advertisement.yaml
