apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets
    namespace: gitea
    labels:
        app.kubernetes.io/name: gitea
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:xdijBnQuw8e4rzlI0Y3WtZh8Ka7Aqwv/OvpVG+jUNbiRdbtx2vObIRVfCE8m+AxaWva/MyA+5pMh+jA4InjLcA==,iv:OKWdOndLYN/QHEnD8rt4c2SNgWJY3d1D1VoDGirSNUA=,tag:kOyWAI+r0p8dFPBR4IM4ug==,type:str]
    internal-token: ENC[AES256_GCM,data:l6fz2cS2D/qupYp9DlPpk6ff4oKayaBUgNesl9AGXy1ZHuTcybKzc38nGhDx/jU9nOUwqVcUFtTl+WzubhwhhAEmBvVIifdKpf2m8r2ET/CXVpz6jTyElfPrHRzn8MuWCFqQm4px7So4,iv:Yzv3NAAPGP81aGaf8FWBRrc4y6YHbRCcLoY8DGmgIYQ=,tag:F0EuyrsZjsTNDy351vtJWQ==,type:str]
    jwt-secret: ENC[AES256_GCM,data:UAeqjXpZeZuGeYU+TdcWDdNDz0NfPYd6DHbRrAimJ2ytFLPeAkm4KEQIuQ==,iv:sn/0Un9CgdBlcBXDXMLSLb5vcD2GP43PSHMUsvJ3Sy4=,tag:Xd0CCgR2pvAJDCpBa2IGsA==,type:str]
    db-password: ENC[AES256_GCM,data:iiNaiyE8eKkGHRxo0TIF8kmvQAU8BU5+ndbKUp32DT8=,iv:+s+nQqh9zS3ylYBcMHnOTseJpMRVLUOjQPY81MEIUlI=,tag:tLVcwY0LRd8Wz0gGqgWFWg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRk1HaWZ4Und4NzZCMlBW
            d1hjREY4R0lnZWZVRHlHVzNZbWJUU0JBQUJ3CkVlWVpOV0xvTVI2d1VyaEJWQ1ox
            Wm03ZkNMN3NMaDQ4MlRLbnVTTnRnem8KLS0tIGk3Q29HWHVvQjlWdGtUN0JMM29N
            WVEvRG1ZcTBkYVd4YmlpdjRSWU5tWVUKUilHie1PuPE99gcXhQzAILdwSFiIW2la
            LaKQp2l+NoQBV4TuS7/ixvH2NUPodhylZ0lzWr8d53JLCacWKCxr7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T13:00:36Z"
    mac: ENC[AES256_GCM,data:yZ+Q/JyuHXhjMBcjlLuIS1lQnXQLd/KDiSG9QQhtxTawTwMbnyuUPiJLWoZHo7kC//OqLgVHHF/ShqhyDJVDhFk4fvdkqgPkc1Al5WJceJTh/fFkQg7da3htYYmi7Yu4rMkzHcfEi2tQjqM2O+p07n3PfXBuGEjQxBCajFUnhHA=,iv:3HVRLP9myCFwiB1TA+SPEqqcKWS3zHJxm6/wnbM54II=,tag:AGiYjSFrq9ZwlX0hE88IgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
