---
# KSOPS Secret Generator fuer Gitea Secrets (DEV)
# Enthaelt: SECRET_KEY, INTERNAL_TOKEN, OAuth2 JWT_SECRET + DB-Passwort
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: gitea-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./gitea-secrets.enc.yaml
