---
# KSOPS Secret Generator fuer OpenProject Secrets (PROD)
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: openproject-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./openproject-secrets.enc.yaml
