apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
    labels:
        app.kubernetes.io/name: n8n
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    encryption-key: ENC[AES256_GCM,data:sToe0Ac7ZQ5b2hUnLXNDFQZbr474A/Dwp95sarsRkL12EMboVZlbjVefpRAhz+DAnwPEN0/ToTYbm7tEScvdbQ==,iv:ikqpxS1hPeXDt4yhQHU0kHaZalG1RU9YZvnHP980ftM=,tag:7dv2jyMn60E7TNTjCqPgSQ==,type:str]
    db-password: ENC[AES256_GCM,data:qFy+PArzGBZb8ttvkHr6+gQk4GFTpHMnK0Z9pLH92DUjDyAmqxFPOjxjKjNHJQpf,iv:rPFZpaCEGK+LV65p7Ta6ijLfCXsC6ViuXp7wxVnePSg=,tag:N4zbLvd2TJwflMUFjl9F2w==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaVNIajJSaStGallXT01K
            QjVkUWlwT0UyVWdTaW1kcnpDcUVwaElSckRzCkNUYkNUd3VEVG0wZ29WNTA5NCs0
            SWdSZnM1Zy9Hdy90SDh3ZWZhTWlmSkUKLS0tIHB6SXJSb3NQYjc0MzlvbDJFOUhO
            NFA4VXpmTVNoWDA2OS9iaDJxM3hxL3MKraoPS73Tper9KY8mTtYINx2B8f5Y92rC
            vAlfWJeHMzNNBzwuCVLJzDn8O4d1NRGZgAFXrP+fVmjVDD0NTh7PYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:41:19Z"
    mac: ENC[AES256_GCM,data:mbph8ryjFJwhvDZaLzsl7Lyylsy8spEg37H2mXim6VKwIAtqV3jNNMNBcq5rE4+Kt1vKiDVpX8BQsyawd7npH47WC4l5S8L3XVNBHsPLnng+sHmdeqkxeKiQlEdEkO8KyGz3963TYNLBpi/PPqcepjySRHoRAQ28ZMPePmfFD+A=,iv:jCj+sH1a9grGKsT15iepJSSXh/b23xXd4dmMv5pCWOA=,tag:/dawIuUulbS3vf86NvRutQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
