---
# KSOPS Secret Generator fuer n8n Secrets (PROD)
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: n8n-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./n8n-secrets.enc.yaml
