apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secrets
    namespace: keycloak
    labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:fXWWtIgERHYqt+ySSxRYgNotIg/sFh7EpQSZypZ//BOJSbgiX1lNm/CApUhYT2tz,iv:lPN/qtmgXbxMnwBE0snqZBN96Za2kY/hVXzDo8306Zo=,tag:o91aR0xeNxpeF6W6+seHng==,type:str]
    admin-password: ENC[AES256_GCM,data:0NpY8I+gWHpiyQtE008v0cg1m9XBhbYHezQH23Ba2qLRvc4TxjmyuDS+lONW3Ad8,iv:OGdUGZn3GbmjBDV7H4kDOex0Z0yXKaaOx2wWrk9wN1A=,tag:wHaaq6CeMeBo2qpTUx2WbQ==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdGZ6UkV5T2JLc2k0UEVH
            d3dNZzNFUDFlNExRRjlOR01iQmRyYllaMXhRCjBxc0RHU0phVzR6SjVLNGZZWlRI
            K3Zwc2tTZEhTeVd4ZDhEazExRGNZZVUKLS0tIFdKdE96Y2dFNWY5RjNVeEJVdGl4
            V05rQ0FTSjNqVjEwVTE2SlhHNy9rUzAKf8M2Vu4tN6FoBQEInpm8bWwgd3kpnqKW
            7bXTiZJYRztS4AW1Z4ym5i4WGI7hRdLsSqNwCxLV2iy7bMOd9tWPgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:44:33Z"
    mac: ENC[AES256_GCM,data:O7tSUX3QlsbKAibnyr5pmP4zLpKpHVkvkQuD30KKZLiS+/OND7LP8EMW2tMypXxnwBBpD42es1bHsPLp3cveezqcTBRB+9TfRf0/l7IdwlHaQt6A42jranfj3KAc0J3YTJnheX6YSFM0TWxf/YkmQmZdenoUIvrIz9rwTmC7Fao=,iv:Wh1sqV67VpMsIdrQzHQRMbpPqYjZpIIJdo/vr99aV1A=,tag:vqSal1pPO4K1IxaH0pLjBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
