apiVersion: v1
kind: Secret
metadata:
    name: it-info-versand-db-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:fXQYJFoFS5q39yJdoc4K,iv:WI01343rsyolKIFP4VihOsMRpWc7vdUemygITsxpumM=,tag:zRz9OSekQT0irQ13mdr7dw==,type:str]
    password: ENC[AES256_GCM,data:+3JIAd5fXQusubCROrGbWV73zhv4M2pdQH7M7NGg5LsAkzOStPk2zqRKfgmiy+vF,iv:VJMFhRY5pXYvv8lFEyjqT0Dkgu9vwM4SxrSqb3AWj8I=,tag:zN4Rpo3LbfqUSYwv1XAY8A==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbDhXdFBVUkEvNXExd2Vw
            WmhmR1JNRFFzeCtFMzdBTGE5UG9iY1Y3aFV3CnZ0cXJ1aVRsTjh2dWpXck5pRDlE
            UklEZ0pTbDUzZUZUNEZKRUcrbEhvTzgKLS0tIEZPYzdJWG1UTjJMQWloTnZGUDQ5
            cjJtbG9RODRiR29HMitPZzd6RzR0N1EK2q/1C8u3EEi+UeB+YnAzJEPxojiP085a
            9RsGYcHXsMbRo/6l/4DpmAvYtuc9zIl2EgwXnkhNmSvggHHIuzsicw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:24:15Z"
    mac: ENC[AES256_GCM,data:k40F5wpcqHqe6BLP2ch54Kcl7u5GTNUCGON+mYJ6DT91bC8VIaEpsp4QuB7oto3LxZkfBqYq9Ne/75VQZPFuzfPLVWEN49ErErtES8xg8DwsbLBUu5FvNfxRsYpRwso/ZVOwGiidYa5piVwjjy1H/QON20++UIy1WqASaIEUYT0=,iv:NyK9OYIeaKoxg0Co90SL+vdYk47v6r5Aeopjr+rBJhQ=,tag:szOa9bIU/rXTv+Z6bsgMSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
