apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:/Rwfa2W+yqI=,iv:Cnd0IR5nViB1KOeXTHj9lheLOlFjM1sGL5N0R6aIpkY=,tag:axrPccoXCdSO1H4/rqYGMA==,type:str]
    password: ENC[AES256_GCM,data:lbLXgmKgIpa+8nxRK1/ciQ7cDthGlptsEaUM7MEwJNLqekcWc55Rny0zKPP2Sw8Q,iv:L1bn/sl6VPy176m4makIFwBiFSB9BcU35yxkAI6yApA=,tag:Uo/NUPxEVq4a2FvDfeDOsg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YTl3ZHdUclRFRmo1R3Bx
            UDN2SHVWdjYzU0NsZnlVMEhhWGt2K0x0NkNNClltSUZKL1QrVE1EQWV1SGxHdC9t
            aVJnanN1eTJueHc4Z3VtSi95WW9kYW8KLS0tIE9kYVdSNFl3SnhYM1lCRSsrdVdH
            UVVCL08zam15MHR0cm5TUnM1cVNCY3cKDebte1eZ2BL6J4FcHcuW65SsVHf9pXtb
            gCanRF7afq/7uQkHSdzfeo/RBSH11PYJ0V+hlBmJphdlLiQ5cUqFew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:21:52Z"
    mac: ENC[AES256_GCM,data:EvKREIUyVBkDAslq1wPqp93AeuyYIgb8obd4JQv3D/kMZxBavoOysqqibO1vThfa8YhEJQDnvmJEDxm/02NJnecPTWJye91sTWI1hMuUaboGU9SHv/scUV5CkaF62m6JBfGjnZeBATNVRQ3e/tMRFi1/fcGGVX7V4Tm6PlSBzxA=,iv:e7I6qK+80P3RTeR6BgNkO6Ocoh/Oo6wxIOmoZRcPbGc=,tag:cvv/0YDWnBDFkAe4YKJAPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
