apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:9ba+,iv:vwM8Ldy99txdIKnjJ99YecTFPhEgeMMYL8aNzZeoQDs=,tag:5+rkQzS8wxkpGQD4evVbFQ==,type:str]
    password: ENC[AES256_GCM,data:QS3j+sQDL4OfCrnub1FPMlr16UEusixTG8WX5V3YEo7Tbl/hIl+9UDNb7y9XgKoI,iv:MYA7a79aRiUNPAaSDsWY0dTFPIW0UPDFezd2qBjc3rc=,tag:9iRXB0XGVoQ/FXWnjq5pIg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic1Z3ckJzMkpYSkVnOWdG
            dFNIYmRZMEs5WWJ5NlZvbHFhbEJUNWhzR2xvCkcrUXVROHNoNWUwcmdweXJHVGU2
            Zk9oajhaVmZxVVZ5Mi9yQkx5eXU2N3cKLS0tIFRyeTNkNWR4bmErZ1hUMVR4T3V5
            dHlRK2h3ZzNpcGU5M2lCL09nNjBqQjgKK+rL0JwBg6g+qYQWjjU6fs76Kf5UBMSR
            dDU8IYq/aTigUwUtoQAdeJCiUhPDAw2Nyq10cPWQkN1HBkYfpjg2ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:12:37Z"
    mac: ENC[AES256_GCM,data:YWXRPTdNfzQF12YKWl8CGliypcZD2Yh1qyR2Iy8NMLDybThUcxa4hPzHqRQ82yYxemmRmA2zAdNZqgJ+mp2oFTVGvzy1iOaRl+V+2afqoVV8bvs8jwDGuFfhiViXziFC+YajIIvfifR+bkEc4CtJTUUSADLSATwu2clKemQSOFE=,iv:5HxWBf54yNzeVo1DyzpoiB1qWBQ+5iOD1I/ssj1vMPc=,tag:VEmpAm4cohDFhs/YBKwTbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
