apiVersion: v1
kind: Secret
metadata:
    name: odoo-db-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    username: ENC[AES256_GCM,data://h0cA==,iv:KzY0d/Ni4du+zDrZ6pNHmyOZepsJQ+Je2qTrNycMov4=,tag:5fDFwnfGozWLYOem2Z1BbA==,type:str]
    password: ENC[AES256_GCM,data:61I9HlqUkE9hO+KTa2c6hRoNQ8zZrNOR6DYcM7q65JNY+lHcP2KsjIfZkdIeSXdr,iv:awy9Kqrsdp/a4WOpS21VnBcMqhb/6AYxmgUqcXrw2IM=,tag:KxvyFXRrrXPBN4oaKTBSXw==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUkF5bkRkU3RIY1E0ZVpP
            cWdlSGROeElJQ2NCVWNBb1JUM1h3U1VmT0dZCjJ0dVp3MjZrTVlLKy8xUmJLQ0FO
            Z2VZQ2h0Z0FZRC9leVVCNVRiNVErV2sKLS0tIE9ubSs4TmxQZHR1TkphRlJZT2NM
            TVA4SGd4WWYvUkkvQVVWWWZoTEZKSVEK0hb39UwqGLcHnPbSsH42a3cnuCZeuHtv
            szWvDTvT2ChoPxPaeifw0IbbKtf7uGH9VBfSIV4gtgNUhYUkxSx/Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:19:35Z"
    mac: ENC[AES256_GCM,data:zzi6osZeutltNT9S9603SZWza0VIxEnbjG9Tyl1Y4vxn6jB5fntFrZIA5k2EmeIjYbUhTbkL9YHPuF61GZpLdTgDjjWb6NkdmLO74BCUJkMawurJSB6/uNcE38NPpc59CimczTam/MlT3CN7H6Yh8rryOBdG0GzZyaGJHjWDQCc=,iv:i2cVXpaOe5V0st+oeJjDPtVrORV4MxmLx5W9jRpmCiU=,tag:rM9sGe1tc5z04/G3aOey6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
