apiVersion: v1
kind: Secret
metadata:
    name: openproject-db-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:R1YxJTCFcmc0dB8=,iv:VDAZGDXovfmLNoJ7FviYJad40pYyCMb7bxm8dP7yCuI=,tag:BcQarhj9x9ZlVW7ZZ6CDdA==,type:str]
    password: ENC[AES256_GCM,data:VysG/SkRzqc0t0K9+r2eUylEvcqK5Z/9KLAsZtKVYwzlTwbCfbYdkoA61PJZ7S46,iv:b16oLTVTnWqdC6uaIwop1rAbfzBAjt997cp3VijkCvs=,tag:km7LpbG3aGXWvhALKDDTJw==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDakoyN1hjSExLNjV5MVhM
            VUowZjN1TmJnYVZuOHFvQjJsZ1pxWXluS2h3CmRZK2hBT1ZYbmtWdkFaN2hkaldz
            OXMvR1MrU09RN3pyamRGaWgzc1M5cWMKLS0tIDZFMTMvWUVsYXZFUDRUMWlvWkk4
            SGd6N1NjSjBVSWp2U0R4UmlIcVR4OTAKs8GD1mI4rwwpeAgIszKuZ8NPmRQ4f87i
            7CfTnhtLdZT8pi5Svb2He1gBeSfIe4Pd8V1TojQF3XPv/sU/Wzho+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:14:31Z"
    mac: ENC[AES256_GCM,data:CEBVySvQ3khZUFN3SakvOg9RlMhhhpn/EYIRq+lgwIbGHCWkrDIKFn/AGCRfTF90yVQePkGgRfA9SFPMY+Y6vdwaCrZJohfhy++AZxmUbIls+L7mjE9KcEBuwrCqHbxREl3la823iEwEHAf1AuesOEU5YRetsWZVLysmv+EdGIc=,iv:NTqb+5zYYlaVx4Dg9cjghl70O48GaPMw9rFAh73GAQo=,tag:l0gXed+YaxW/HtUVsONubQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
