apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:8lpx+EIzpCn5LAA/BxyozUTMeetdxyu6WZB7b8WH+RA=,iv:CX3YVPjA+fVSs8J7lLoYmU+zv7lM1Poj2qPz4PXbX9g=,tag:b0ubKwYRDVmO4RLqdqxoFw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:E86fzK07lnnF5ByNcMtQOvJXpDkQJadrPelfTcCQpas=,iv:3ZNIfbwXia0hCwa9Mq+EXBleDFePzvaGltfhHCuwgy4=,tag:ZOAHV1qSvP78SzFaEw+GNQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:0bzUcwVZlUPpfRtII8xkheyMTSitSTldPw==,iv:EX1o+FRv0StXXSSy7Kf3o1Kj/D0ostaEbj3swxaZtDU=,tag:ItIHGwuC16fx6qZnvoprDg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRWlXYTdjOFR0MUFSbklT
            R3IxcnZVRFBGNjN4OERIcWhZVVlzS2dwRndZCk05QVl1bVg3TkNIamdOaG1FRWo4
            L2lORGpvSytWT29KT1RlU2V5SXByWTAKLS0tIHZDSVovdWNPaDFsSVN1MmFMRWFQ
            bnVzbVBzWTVDK3JHMnJRNE5LOTVYVEkK5e2LTj1uvuxrsb1mHAyNPtBRT9/BHu9O
            UEDNhJPJySOVzGh5s+1HyHHPom/MYF5K9Xk4DduJrVt5MYcp2LmFTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:52:33Z"
    mac: ENC[AES256_GCM,data:0+Pe2VD1Guh4K0QDIj9btH+edUDDhdK5xAe6UwtBTIZ+iHe/gCPi9xkivBKazCYdPpfj2aLejbl1PPXq62yjXIg7+I+P8+rsjEDRJmZdDeRtMkBY7OVBxF+cZAH+RorYLrDnuttGFXTij3fF4EqpRYmuFWf/mIoam8V1A8DDKV8=,iv:tsdjnhwoqMCpUK7WeBX7eY52g+KqnCyTi4mMyyW8o+w=,tag:2/CENaMgeVspfrqN8n874A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
