apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:hKs/z3CAdVreQ8LTY1qJ+Mb5mdAfJBgSCKb5eJr/F0Y=,iv:FdnT5mKzbIT0NIayXjAng33pUgDfliWa+xwcJ8YCxow=,tag:FNLmchT51YH3aXZ99AI2gg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3Du4jXF2zHWl0zv7ysEskhYpAvnbqNAAbOXkS0mKXHo=,iv:bmKWoCHMQFn0j04Qk+9ClUQi+4ZDJu1e11VbMc6AA3I=,tag:zpP1ZlaXyn7hiuC5G5AmKw==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:BwyqGmRZd1icesVliNhpnLhorRDGCDtva+s=,iv:tit1vJQ5LfSAxPdg8inLQX2bCZ9c6FmS9+QYT3TFiZg=,tag:Qd2lD0U/edr6lVZF0SxvIQ==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSStUV1RIMER3d2ZUTk1i
            aUJFcG1rZy9pZDNFaGVycWZvcXFNZVBhc0VjCkovN3AxSEZmR2FRcTJ0THJhNlVi
            SDZOV3lsMXhJOXhtQXp4NmEyYk0wQ1EKLS0tIEw3cUtjZjJ1Qks5cE92MjV1VWI2
            T0hVWXpOdE9ZQ1FpYW9YWlc3ZDIwdHcKyzunzBkwg4u6PRkO88cUJu4bVZWIg95s
            YWM7eGzKuHETH5xMwSr30t4mioR5YiHgcJWJh7qX83MxwH39KIBZKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T13:21:47Z"
    mac: ENC[AES256_GCM,data:gVKvM8+RTo1bP7DkCRlnTRiJJX/vq0ayyUuHSHu6BZcWo+jUVGsltzNVy87JzJcIMsjgN/4CgRzJ1kQFLRZY41Xqaq/OOsyacvc4q8QPFQ3Oxn3yMwzrOfwar/CHiS+GnfSaWoH7Tgm/Ug8C74xi82i8TEFQa0IgwPl1AyIqVK4=,iv:DJB/Bo4LeYPPixz7w3YjcQfy7ZWczbA2r9efZjc+dDY=,tag:kNQ/RwRVm8LCzl0ziKxcDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
