apiVersion: v1
kind: Secret
metadata:
    name: garage-secrets
    namespace: garage
    labels:
        app.kubernetes.io/name: garage
        app.kubernetes.io/part-of: infrastructure
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    rpc-secret: ENC[AES256_GCM,data:AEZdnv8oKXU6xfQu9ZvEdzTWzvQbJyLgaQBgEzOxaVEAm0HpK8TZ1d5eF/fvwuj1dZc8vJApzrqn+Nj5+IQ8aQ==,iv:0AYauturvMZVH1ufgCD26VQBv75muwmFMSnvat3ys2Q=,tag:6mIxKlP4AGJsHvUT6tutAQ==,type:str]
    admin-token: ENC[AES256_GCM,data:7SAbAo0At/XofDf2H4SuKtn3n8krEav7EuQT0NyRNbDN0f4oV5uE6ppb88J0Ajo1YrD3cOTJSO1Uo6XVX1EGAQ==,iv:/MNVa14/6L1Qs73AgHk1mmfX7cAoNp/96zccZZ5VwPE=,tag:iKpQjEwjai+YZnLbNc4csw==,type:str]
    metrics-token: ENC[AES256_GCM,data:ACTlMO/11viu/9acjzFW0jTvVuc4hO8bh37l5Ojzipe3rHWA4VVIvwbh2jUiazXasOyRA/qZ3EqbywlnJ8eh3w==,iv:6QGUcQXXFEUVh4xHLHeTh6qEuCQlfC6gK3lZKAO0s5g=,tag:WbMsn4Z0oZ0qP/qJjms+2w==,type:str]
    webui-auth: ENC[AES256_GCM,data:qFUamawUNNWbNLyPY4x8AipBpY8RZGxmFaIXDfg4EYfzhwB7jOLOUmJEsx4HGesbGXgcDdNYN78zIK9LqD5FcmfJ,iv:PEJsU/tED3BnFpZyes016Vm4z9fD9obJRY+UgrWJgfQ=,tag:KI+NY5S6ownu4dG9dNakbg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTzBSWHJXUEl2WEVubGFD
            c0xKRWpIOGcydWtJWDZLeFFObTNCcGhEYnh3ClE4Q0ZEVWdvOGhYOC9BbGpjMHJa
            K2xGUHV1Smg0T3JIODdhRnYzUjVWeTQKLS0tIFdmeFdFYS9ZdnIwYkcwWGZYK0ND
            RG5lQ2VtNHh3L2ZWNkFZR29nZnhqek0Kge9qkdgSWEUFZ/DJdy56flmAnVSEOMbN
            iqv0MzbrLdNIfiNbrbg6ZGchUKP7+xDdQpL2qFZ9/rFL4p1xU+CKxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T11:27:52Z"
    mac: ENC[AES256_GCM,data:460CCgOSb6A0weQ+gLWJZmoqmBR/kXGG85QWgi2YB4g16PuljT+w80354yJeoANL9k2cKmlgQzzEmjhh5hx5/ZDXxYx1/VFwAXoCqiTu+QhHjId3p4SU9vP0Agc4kOSp0MKqIGm4D5FNho4KJ+YtklDEzUdDgumWfIyf0xppmSI=,iv:sHTg+bLwNCEBBlX1vu3tCHh5QqY/4jY+KtEa9e73sm8=,tag:hELJHh95Zrseiz7ilFfMWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
