apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-credentials
    namespace: monitoring
type: Opaque
stringData:
    smtp-password: ENC[AES256_GCM,data:kgc0oJo1sD2siOFso55SzQ==,iv:rvQW/VypYL2BoXVaNgybxJ6UiE9dQXvrxY4ROkQLqaY=,tag:uNH3fgiGBTl3A+Afbe6gIg==,type:str]
    teams-webhook-url: ENC[AES256_GCM,data:uK5dDMZE3fg5GwF/DAEkDcJkBXv9B0YZgJlax2m4NRsiRAKKBE2+shiN9c+u+nxLbxr3LpGc2fJcPtg30R4B66yLF310Pd9C37RxTdpJPwJ9D32UeeO4ab1MMKAC/0ww5N+Ah2k+Ftv+v9vbLYq2ogwEHeSTjlGNv6l9Bogaa1ELZHsUe5IXNe79e6GyDYzbObTMsaT9jTzXTy6jQjfXr93cvoHgv/GJ4P/WxlYCP+iSbPUjsLWkJfJHe8LUDO1FVhrXIZppEugXqDuA3R7W1GHuVeWFT5+L+rddE99eUyZ6u6VMboBPMU5MYT9XlIRioOBjSHI3vx3oXMf8drG9CAmixTxWBzn3uA4j009zxQhFZPqjmyZsMRs8QorS/A==,iv:EZVfRYj9Wet9Rofh8zVgU/0gSWS5AABRxV6VblwcoG4=,tag:je90WUgLyRph0a3F3Ecamg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYzc3dlVaTzNxUWprQmp5
            ZVozZkc1L1FIbkdZQ09uZ0J1V1dROUt0cXowCjM1NVBoMmt2QzE4TFE3Wm1wdG9z
            aklpVWF4TlIxbDh5M3FHQXdHYU9pdEkKLS0tIC9IV0ExUTJ4SUVpbmc2YkQ0TXFh
            TFF2QUJTWllYK0ZnK3VEZ3J3VWFVOHMKyeFy/yNtgjkzFlGJzkKsrvbf9COiPPQs
            bpw7C8hoQm5p42FtLQVnXCXqirbFtPG2ys/7S8a5mA90HaJL9bRjBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:52:25Z"
    mac: ENC[AES256_GCM,data:uZf0Tb0rHmQHikMYUkJPhuw63SPwaSiTy71W8zvaIPLTVQD4rDP7BewztA/U4lMqIT7zsYQiP7ldecWtdwjdxlyM4IZ1yJdTY3hfOX1U1t9pUIGbV2IB08I0hT8pokiIChyYl5x4JC8RCKRjYG8fohXpZvjkCMHFrcdtTCzo+uY=,iv:3lO9s/T7qigBP2Q15UFTuVnEWdTf0ofwBHC/3S74gOs=,tag:Y90MY+7DRU/oHnljUjTqcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
