apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: monitoring
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:WO/tnFY6NpgoFYLVeSo96N1RKRmh9VswENQkf1rmqFZ+cVFYd/bc9QIedjzfGmPKUJnKRkDor9kKVLb1Zhn03Y1ozGmI/qa5PjPQCQny6Xey//GnY1ddBNKQGQUC3VFdaW4cGWd7ZbRstwyKkFMhOS3tWWDnZTxyyJzJysMb7Pp4eZ/Jz7oapMj4OyPbnuEsMjGPWvr9zexyx5A/1DLsw2kl8Gn1+ObxV/i8WxiF04X9Od6e+n+HPR1j8Pn7r94seI4nffUinM35rkPe1GrXRJP9/BDpohDly89diUZ5lw==,iv:EBpJ9L/eW0MxDBipmMlON9x0hem95MdvsQwbimlGddA=,tag:sdBK+QqwZB5b6yQgiPo/QA==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdjA4dEhEQTZxQ1Vsb1kr
            TllHQmovekEwSUF3NERxeTZhcGd6TlNycm5NCktIbWRxYURtUXZsLzNkT1R2M0xj
            R2NCOGJvZjZtdUQ3UHA2YmVQdEx4ZjgKLS0tIDJoS1lYN0dpVHI3WEVMdmd0QXZw
            T090VlhMdHVtcGxCQ1p5cHFBbWErM2MKdQqq7765ybnAMBeq/9KCO5ukoMAzQxOG
            ksiV0Two//RnuytDO2I3rjxK6r07BrnLUrVwg6AJKDwkLJ6zWiIWGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:55:33Z"
    mac: ENC[AES256_GCM,data:zgKun13qjzxx+b6FTZE7NABhdKZxGfFddKqFoN6Vy7FSSbe/eRqsFSfBXAVOrUb3yz/hD301z4JOLn934PcAC+7c0bOPtyXBES8ktrgAhsSnAM2bV1FiD01kM4BXvbohfjqfZdmW+/Oc+dmMPziNmVKfaqV4vfDfaIpc53LfVIE=,iv:HokeqrwQR5Yj+jIvVVR/6PyCv3RT9lCyOf4I3alYhYU=,tag:c8z1BsLWduH2aqhY1sdIDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
