apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:rEDsUDw=,iv:9rrH5DB/5FcPv26GUrU8fj1grsghh4kr0rSi1aUNdWw=,tag:S1mBAqhk7tKrcmAT6prtZw==,type:str]
    admin-password: ENC[AES256_GCM,data:wei0Y70IhGs06N1PSq9IVGyb5psNow8R,iv:B9Zrp0qi0urDWKrIbI+oh16mOCQCOFzhahe7MrRMvXQ=,tag:EpBIBV2FRohNp3eXECwpLA==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYmRJdHp5VG5NMFJuZkJ4
            MldITkJ2bnNuYitvQVBjUGtEeUtraDliTkNNCnVDejdwejFkSWtCZFFGV3lORTVa
            S2RlM3VRREUvQ3h4RTczdld4dmxHaTgKLS0tIEQyNmUvUmlhYnRycjRNeGJjWDJk
            QzREd3V3ZnByaEh6SkV6dTZRR1g4WVEKpW/2t3DNsFw4R9nywgBZmgQbCfJNt6mL
            kqzUmsoWSwdkZMu2WEuErK/Pn2psSdbCjGmrY7Ybs2BbjqXbbP39vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:53:05Z"
    mac: ENC[AES256_GCM,data:3NwfLN2Tktyk3mBvkjnZsJrwYawyGFq7p+AVw36Klz0ccWnem6q4/W+Jla3amWll4z1OOIu0arfEb01Pjy5lSAfyIRcg6DCI3wDI1X9cesLlfXkw065ULJhoRH6Qvvphxm/BsrG5OdwyM2JvLxg/m/0ZRslwwG2b4UwU2QRvmSY=,iv:gUkv96saaC9YuunYVP/Ce7KM7S5BGAPdUzMgEowszS0=,tag:dKny01Vj3dpvf8iA993hRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
