# TEMPLATE - Nicht committen! Auf k8s-mgmt-10 ausfuellen und mit SOPS verschluesseln:
# sops --encrypt --encrypted-regex '^(data|stringData)$' \
#   --age age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm \
#   thanos-objstore-config.yaml > thanos-objstore-config.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-config
    namespace: monitoring
type: Opaque
stringData:
    objstore.yml: ENC[AES256_GCM,data:QZvUmNfOKPi77q9ZYnLjy7qBOnRRIQNK37MlzyI5g3QFDPW5zE11NFvgP3LKSqRXdGA4NA7SWWbS6UllPl+rWs3fWtNJAGJAZXSZ3S3VHS/xJNWml7UUNYoBCVl4ZtM98+8ExSOGXZh/Z3//zv2ziQZ1dpNaR3L8oE7UWl6ZetshBSh0/E9gWc8X70r1aWk366SZ+yEOhpDrx7JcjzMRuhgm5zrKxR5DOXJqLLcGq6PI9mfWwpc+sXnbYs63iT4mnlVomy2zjQFggcYWjoLB7e/sKvfoB/AN/odRpkKY5zD7H0tjbphcX5FxS0Ooc00ux0Tmm9B/umhHJL3zKUKSeALyjWRCrYRT4Z3HjmIp++SIhw==,iv:4xFS7GGpwig4iUizhS3IXl0V48A9VqIxIF+1wY6BRIk=,tag:b8l17M9OaLCIB2A8f8dqjA==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUWlXMnRWR0dhWlNZL0xk
            eHpKTFlEUzRNeEZWODhubjlhRHhVWHozQ0NrCjE2NzMrWEtaQ2hGSUE4aUxMQXZF
            ekdBU0tjMVVaNWVtSlppRHVNRjVaem8KLS0tIExibXlnRmF3SkVrY1JPYXovVXF0
            QjRFN2x3TTJOc2NUenVsdnkyMFN6OHcKwGuBQXJIPbtCUokm1e6bB3jhrt58/JXU
            r7V0rhN3kLig5ARyl88p+qT43W8loRwodcYRqe+0EKjObxcBMCveUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T07:20:35Z"
    mac: ENC[AES256_GCM,data:0f3mcYVgJb1lI8hF1+N0qbJinyqs7B5+hICfMYc46rftova4SH8sW3bmKLakTwzJ2TiK3QgfjFS+lN/xPPDC6mUqqfv2XDdjPx1+m4JfYlv8HL3rQ7ObyM54uABhNhu4vgXdGu+jGK8tO5+TiPCKsEo2ioE0hl/eV0rbJHEl7cA=,iv:F9nt47iTPX/9Ma9AYxAy9GNvaS/vPT4U7NrXmlzg9Ec=,tag:+zzp3HAhnAiYVLs5yagwCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
