# TEMPLATE - Nicht committen! Auf k8s-mgmt-10 ausfuellen und mit SOPS verschluesseln:
# sops --encrypt --encrypted-regex '^(data|stringData)$' \
#   --age age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm \
#   thanos-objstore-config.yaml > thanos-objstore-config.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-config
    namespace: monitoring
type: Opaque
stringData:
    objstore.yml: ENC[AES256_GCM,data:yIjMShL4QlzFRhyNNwSCsmxzOo4KW3dEAOLlBZebmI/5nyn93I3SkbVRAIZOkHHvyDXyUvxCaYAzdk2BXnLxYFtuRNcapkC8yEC7qW1LNOWSArbUcnV4+SGo1LDnps5Eqm3Yb8fBc908K83UYGjySxy+82yZbQTO8+13uZUCMwjDUj7dOfcbwgHZZ84bN6MPfpJxTysBr6Gz86IXGmUdHiVViz7Tu4MjYlT6t6RHjZ7J4VOcU+OKb9L86y4X8W/tNKxz4BD9wvATAfLVF16mFiY25QbzMZ5TA6+NHvBESNwi2J634yw70seRVF6O+3CEc7IdbzUlO89Q2w7m6B+5JyJi94/llh4Q5aw/taftay2DLw==,iv:d+yAWVtB9gj5/68Py7mGEM0hYigrvj/E8GcvGYhAii8=,tag:veXntwFdHYiVnbYYOumg9w==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QkdIbEtlOGV6a2twNUp5
            aFhUNVAwblN0cGxIQ2hTZklVNkZMTW5MVlc4CnNxVFFKYXAvRDJ1K1BCUmxaZjc4
            L2JRQzJiRHprUHRDWHRkbGVkK1pPYTAKLS0tIE1zRHhyMEZDemF4Zmt1L3VmQjEv
            Sk5sbjdyT3FveTIyemZZTlFGaGl0akUKYi0E8NuWKu245iC/JvaT4e9yvHi5pdgw
            SwAa/4nINeF1NQPXa1T0JGrEpCtf6N2M9hV9aEV12LtWxRwnGHH4zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T20:53:25Z"
    mac: ENC[AES256_GCM,data:m6nJMd/7ifgCwmuEDJHeMnTXFBMRNHyCCc3AwIZs+FjjC6tq5WkMN+Q+u66cCMOaNzcSzXKAKv3C8fNgdL2KNNrU4yZxuHnaKWEW7Mea8GR4IPPmk0xyOTPG/slvDUttKgBzrexpzUICkq53nY/y5jrg0KZQPVEo3z2uF3CnMFU=,iv:wEPosUA2Debj45zEMBPN4nAwNbtjMQHluER75wsOETA=,tag:taJ6Zu4JaaI3TULm+iNLcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
