apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Basis: ArgoCD Konfiguration (KSOPS, Cmd-Params)
resources:
  - ../../../base/argocd
  # PROD-spezifischer Ingress (Certificate + IngressRoute)
  - argocd-ingress.yaml

# PROD-spezifische ArgoCD URL in argocd-cm
patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      - op: add
        path: /data/url
        value: "https://argocd-prod.eneg.de"
