apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: monitoring
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:4TYvV0J21KI1OaPl7UYy6He7StoFhPlt5iNQFuPeKg==,iv:kdIaDU7iusjCpcIzykhTtQVJqMkqR0Un5lZCGF1PZjs=,tag:jUEnZyjLaoSGONDmPYxzQg==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:ADrlu6rFEjf57UPf1GG2+56suqzfO1ZkqAkeKdstAnM=,iv:hDPYZvrTx7ZTuLj3pZBZk+5WqQqtwh889Y4pgwJoHpw=,tag:aMlwBIZtcYIVJgfKKT0sMg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RTJyMk4zbnVNN3dON0Nq
            VGM0RWkyLzJvQ09OV0JvaWttSFZ2OCsrMGxNClVIUjZhK1dLeHpzM3BiTUhRN2Vo
            cFVwdVFrdUxYWnZXQU1zZC8vMHhtZWcKLS0tIGJJQzFmN2pwUUlVVlBIeEpwdG13
            THpTRzVIcXBNZ0dnMHR3SXBPc3RneTgK8ASxp/WgvK15/h/06HOPDop6CS53TdVf
            pwsk4OD1PovPskMrqxca71flIVVRUFXnjPPh+OyH0mtM5GPR/nX8+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T10:46:54Z"
    mac: ENC[AES256_GCM,data:tAEcfodGZjmtLH+Zvgqn4rR+XfOhoNQESt2ay5vEGSli6QjTT2OIEFQDFR2vsvcPCkisrhspk1gb6xXzei1S2bsj8y0NOWC2J5BzpPyxXbGG0txnnSkfSr259McdXnfbQJNCCe1rzStOjUFsbsQ6JjT+G9cKZMZN0SI6ZGGuMSU=,iv:obKScOMwMn0KVoXQMcHNlF7DP08E84QolmoCjjW1XlU=,tag:N72wR9nyzxopyd8lGE5lfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
