apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: monitoring
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:dXI71TrpR+VfGCUgN5vx/vsgV3NqozoHIJzbjWzyFw==,iv:UCa6I74J53xVIBMw+QxYtb75XXYsfh+7Fqmvvw8siJw=,tag:FD8go289l5SZh7qpcq2ZPA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:sB/3A3F2zO33gs/t0Jh8d405/RRkGto6A48WewuGPk8=,iv:KoknZcnPgcnWm6f4Pxh0maPwMUMfxn52ZrzGU/gZIC8=,tag:QRuHxRUlKUZDUaLOqYU3AQ==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMEtlRko5Mm9qZkpxNjZQ
            MXcyKzR6RWdoN2dCZy9lQ3dQV0pXRksxU3lNCm5kUlFxZ283alA3K1Z6S3ZoVlhD
            eHRYOVFleFZXc0x2TndJVVVwVk9qQjAKLS0tIEg5N1hTVEFXUjZuUDlvcmZDOGFW
            bHcvMUQ3ZkNMM1M5ZmlkaUMxUlhVSlkKQCpJVM/aOK+ApSzS/C46O8yIYqIFcSOF
            MQzS8BDI6haLvOpPzgsXgcginErreFJZt586hgM6CoQcrmEEtodIYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T09:52:03Z"
    mac: ENC[AES256_GCM,data:wCEzQZoF0fnRfu1b7X0JD6HNaFjFZy9Sz6fpPgGx6NZtPrNZ9AcXOuNMlK1yTF/UFytsjy08kdYAU9sbl3uKLnSRsLv5eEWbLM0rY2e47LpGdWlBHgsGq3niTTYVMGGvAOMeQ0K6Lu9kI1bLC8PT6yhSotC9L0HNnzZjpw3Q0Hg=,iv:3/tmsqjg7JdsuZ+WCwQ3FF7/E4WzXvYJxHUE26053h8=,tag:W5yR45dHN0zpVh6X7w1xPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
