---
# KSOPS Secret Generator: vCenter Credentials (svc-otel-vcenter@eneg.de)
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: vcenter-credentials-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./vcenter-credentials.enc.yaml
