---
# KSOPS Secret Generator fuer Garage
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: garage-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - garage-secrets.enc.yaml
