---
# KSOPS Secret Generator fuer IT-Info-Versand Secrets
# Enthaelt: DB-Passwort, Session Secret, Encryption Key, SMTP, Keycloak
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: it-info-versand-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./it-info-versand-secrets.enc.yaml
  - ./ghcr-pull-secret.enc.yaml
