apiVersion: v1
kind: Secret
metadata:
    name: registry-htpasswd
    namespace: registry
    labels:
        app.kubernetes.io/name: zot
        app.kubernetes.io/component: registry
        app.kubernetes.io/part-of: infrastructure
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:kW57GYt3anECewwZm2mmLdxWAXXxmLqbDzjBwkybJISnZNTZq+GjFCmG4G/tXFrJa9tqeR7V+PB1rxxWI96ikcyuke4UWXOGknsvGun2AEO4zS2T1yNoUoxj2UoQp05GzXrnJJR+XMeCv2uiYTz4bsYpI/fQ8LQS11HcGvL7gqe/YR+uETnN0TyI5u/i,iv:kOsBuBBUDrY4X03PAwWZZoNVUxLKHWMaqkgb95IlKfY=,tag:UBdZrWsuhqDDCd8geF4Wqw==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUzhKVHRTdXZHTzBlVU5L
            M25ocDM1VlA1ZDVkYjI5QWtoTjNINFhyTEEwCmkySmxuMmMzY3dERE9zUjZZN0hz
            MmRkbGpLRFpyWU1NYlJKOWpkd0NWUGcKLS0tIFRJZEdPaklSWU4rUjhOOGJ6RUR5
            YWovT09DNi8zNnBNNloxUUpzWVhoS2sKdIq25BEA5px9rquPAT721HRXUpl37Oow
            U3dYIv9gLYXNgTh4PstBjcMkq21UQI3ZdB+zUwRqASqG8EuSg/afpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T09:22:33Z"
    mac: ENC[AES256_GCM,data:q8LKRQQsUlt6AWr7Lc0UTYTRRDiELLtL5pLyJ0pkQUDUa5KZCKWyDdm6Qe3ElRqeyXIUpTJ9svuySBKpLenZjBsneJGNFvmnVVfMtY0qMOo6wD6PGxDAVyc7ROl9aaXlMI6Mswq778nWRKkiZZbxV6By4DOV5F9s6LM9mlufiic=,iv:CzK9F0AQeZWo0HYcQsj/rkafqEkmrNbwpoK3bIHkgYQ=,tag:UE0F8UQEmz7npmSKfMgH3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
