apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-credentials
    namespace: monitoring
type: Opaque
stringData:
    smtp-password: ENC[AES256_GCM,data:AHJmyjM55j8s4Xkar42nqg==,iv:rZGER7ttLf5tAgfGQkhwN5jL0lOqHMezYJy59/Xwwpw=,tag:rLRn0nG+i9UhQyYn+9Uk9g==,type:str]
    teams-webhook-url: ENC[AES256_GCM,data:eRyWrefBt8OBr9rTJ0hVIW4I3zkq39B5rJaki+aJ3uyJuxMddQ4+USy520vOKo4J/OUOCSor0JZktZcZl7v4tB9ZxMfYrXl5Jp/x4Zx1h2MDGCaRWZheBd/wWh0Y8UNcQyut/UitvNTD7DptECg28rURLRpED6USzUjacril9+CQlH/6nZb72rwgSdYWZzbd4HALtcbm3m4JLIBh7WomBwKLs1tKzzey6DQXh94uL9sJFd2zhBOACuGxR/NlnLDWCr2Ep+ofZis+VezrMQtWr9XxEwdrNpR/h9FpnXhyTt+CM9nBZznyrov68uUW79Mf30mgKQS2GIuts+LJWuNQOtGiVT7aDkFPhDv4DqiQVa9oj528xqZkQw5nb1Fc5Nu9wzQ=,iv:/b5mTgn0F3DXL4EyJhMVglUB3dBKA/eE4qFlTTnsE7Q=,tag:Yf8jIXRnFAhvNR7u64fbpw==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcFBoeCtja3FNenluMmxF
            SkZ1V0ZvV1F2UENSVkJJOXM2a2ZYd2xKTjJjCmY4S0Vld2tJSVpBL3ZBZjZrc2JT
            WmUwZW84L3lneGNoTTE3amEyU3RqUlkKLS0tIDhMNUxyaVRGNnEzSmx2Z0g0V2JU
            WG5KeHhrNnAxS3BGMTdyVG90RVl1TFUK5Bx4ZKazf52K1tbjsKso/Zei11b9qhKl
            cIy/jZKjxG2ZOsX5JWWbDflG8My0HXVTpMuWw42CqUThV36Aoq3K1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T09:07:00Z"
    mac: ENC[AES256_GCM,data:5458/v/ZZyxu86dmR62LIJEF7XEHFQYlpkDSTfEV3FFvQdNUXH8axYDnxUQhGjZFhJ4uPm4AeuQUdftBdkh7TUiehL5QjHvSL3m0MF5KY6JeetmEQJGfLirFsQToDz2GEelY/i2w3DjpkCi/jnOjSYe15P3X1xla3uVgpzMRxFg=,iv:RiqX3WgyEs/PNioTV6kc63QOmQrLazbITKUk7frpr0c=,tag:Jm3PUhd0ahYBEqAcq8gomg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
