apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: monitoring
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:U3SWrJWuF7VeEmNY9ir4Rd/4B4aczDe5m4tig5GlG7x+IJe0L/lzrBwP6IyxSNbUZmnV7CaMnDj7W011Emfg1r/18/UZsO3wX7cZScdPvIWaLiC7mvBKafCOye/0bX1PIytA2U8yPMIkstswtT5Xv3U/1qizdk/QdPGg9pLPgCOF0LI1fMYD60IZnVj8wjv61l3oNhmstFTjYnENjV1TmKurE4DIATbxqjcaqfr9picgehZm4QVH8hmIzTSH8UD59a8oHP/nuqFxSTDMcaadj8QKsAuqDpqrcmewxOeQCg==,iv:9O52kkDKBjSyK+e7UV1XhALEtvLvpOKwGk5xIfyNpJ8=,tag:09mEt7UllSxRX/FLrcbvzA==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNVc4NlpYU0JYUk1ObThz
            dWVrUXY2ZkYrWUlFeTJDV29LcVV1RG5pcWpJCmp0aGZEQ3FHcXJROFdEWk9QYjln
            Rm5WTWJ4NXJXeS9odUZHM2Z6MEV2MWcKLS0tIDNGMDBMNjlNRDZiSU1DUitQQWlC
            cVdxYWJtNGlGaWk2TGxSR2hSUjNVcG8KV+O81+/JbKGmBtMKTzAkWjrX6IbB8Hjx
            5Z7XilVP8T/M7g8Cg9qLnIiuImayxJhAo4x6MBKJ/TBz0ru3vxHI9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T12:54:28Z"
    mac: ENC[AES256_GCM,data:uDc8sKKbJeiGqd7FufjqrSiiA4abr7Htw2WPbrjZ2DFHULgsoHoPdNBwCidg0FaZ6BhH75R1LgnnuYv4vOVdGlil9we3g1CAmcfeEw3/Ed+D/+Av2QR8R+oBPCPu2wvIojM4stGlbiP0S9bRfv2S9ank9RHlLn310zvjsxLTRVI=,iv:/VhGE1Q2lC4679kCE2asPTZ1l6MSEQA0MIrSBvGh6s0=,tag:YWZb7Ch8ipyfm1DQaEJXkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
