apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:5dw8wTI=,iv:sDr7pKeAZstZk3iWVcNH0rV4BqL7pOTsAN3lwexLceg=,tag:Bi+1WBTsz6yD4vvxBzp6HA==,type:str]
    admin-password: ENC[AES256_GCM,data:V5WKTkmVaB3DzQ6G1Rrs8Q==,iv:v8shvv7IXu13nfRF+7Hg9y/rkn/of0eqANJmYDEiAlc=,tag:ZJyIXKoFkn/VnAG36wTaIg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOUlsak9DSC9IMkNITGkr
            ZitNUmw2Wi9RQzNCd09BWGlreXUxc1l3c1ZJClVEN25sNk4rTHh6Y1JvSFh4ZFFm
            Q2ZrWG85RTl4THIrdmxVTFJEZjNzQ1kKLS0tIGJCdm5pWmlTN2xHOXF1c2p2empu
            SmNGUWtmWmZhb2xHdUV1VnRWSkpzTnMKXkdTDGvn0K0RAbVC+8YZy3+l/dlOuqfe
            +YZ+J98Wfikw0tfsgs/WyDMOxI8phoHemGUU7PZ+zL73WVT6R9XEfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T09:09:33Z"
    mac: ENC[AES256_GCM,data:sTX4VzJ/mTxQzGRQ9OsWk/GsVePw1eQra358ackxvtCbzwzXQBHjqqa9lCYejQB+rcDqbebM4zsfKOGYR8zcCL00ej9Dr+TR8zby8qkWsjjMj/YCVnev5nAGrcJh99UfyWzDTqRfzHNwyYwi8vXZ83X3VZHUcTqJ6SK6DsHEm7k=,iv:c5TrjSIAcJ1u8C3WjMsPqcLxCnyC72Vxs7GfoIxC1/o=,tag:kjCtCihzOeg/byeILvBxUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
