---
# KSOPS Secret Generator: AlertManager Credentials
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: alertmanager-credentials-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./alertmanager-credentials.enc.yaml

---
# KSOPS Secret Generator: Grafana Admin Secret
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: grafana-admin-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./grafana-admin-secret.enc.yaml

---
# KSOPS Secret Generator: Thanos Objstore Config
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: thanos-objstore-config-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./thanos-objstore-config.enc.yaml
