apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-config
    namespace: monitoring
type: Opaque
stringData:
    objstore.yml: ENC[AES256_GCM,data:azIIdjA/rmTnod5xSMqlCOKrLCg7BwcuiEsnD4fsqvLFmdV9W3IjL9PNbHeTkjzZFffDetO3bq4lu62hmkzaYcS6MqFdG42x4bI59ka+yEPDLNuCujkAywia70V0oilKbX+JirKbq0hZdxeVUWTbXF7UO94oqSRyfvouJbTEClWO6ft/skaPv2gY+gTKYpjVaRF9cvHBaNNVykTyUeTPEuUV53zIiTgcrBUIOuio6r79jOlbw15TTtOH177byIRvYgW9nKsSBZq3MOl4JL+mbvvc5s0ooscfY7QlNXRYQh4F+Qlcx1FtuBzQ1Zt0oTBZNQm15P+XWNlKSTRzMQMIDP5BVf3zIgKSSalw53vwdUY=,iv:JWM3229vQ7G0ekVHFETtruyqT7xyUjGE2L8yHmnQVfk=,tag:BrUMv0GSBd9m5ORjTjr5Eg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTXdFNlZHWHRRYmtMSXNJ
            T0k4bXowbDJacnRwazQ3djFGazBNSFZuM1dzCjNaaENXS1ZQdjRKWlU0dlI2QXZ3
            ODNUTTVnS21Cbm5VSDNZY21YazVCZU0KLS0tIGt1WVR4dTF0VnFGTWIzRmlzWGFz
            MlFKbGN5TzFhWXl4YWdsb0kza0lRc00KGm+V0yxXhcwLSc1hrzJPy1sMXietUZoo
            xVLa9QkfOubUUJfo9Oqe7kWUU1cJKxA3cHdfJ/ENO9woT0It7459xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T10:41:37Z"
    mac: ENC[AES256_GCM,data:KCIZrQNwhry+3MXCJU4fAEgF8RhEPphGIjMa/SUGTruckXXqpFC9mZuNe0XWYq/sQWXWqFWBHkB4e/3KPgDeFKvz8URTTrsdnPftWYTzkFbf1D/0s68b6Bkp+hN1K1mBInCg+ixTSjxFCFc0MiagyMdLTsk5McsLuHnrY9EaZyo=,iv:OEsAmfl8PKecbLrsvt4uX4oWkDTui9wDfiqcnCsYyqs=,tag:qU1bi24JAirPLCNqe8xhGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
