---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: velero-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./velero-s3-credentials.enc.yaml
