---
# KSOPS Secret Generator fuer Odoo Backup Credentials (PROD)
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: odoo-backup-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./odoo-backup-credentials.enc.yaml
