apiVersion: v1
kind: Secret
metadata:
    name: idoit-db-credentials
    namespace: databases
    labels:
        app.kubernetes.io/name: idoit
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:vYRWIGJholoDaEgtprpr5jrKmEdnhHDpbkh7C73zvth9pOsy2p7dtkCmTXoB3Ffl,iv:9Ub+wWFW6H/oQdu5Zx5XEem7aggj7iulbvrAYnp6wJc=,tag:K9Z/MzAuYEomz9Ysb06tIA==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMWhBTWhtakZ2Zk1IcEVT
            SnBUNGJGZHNQcEJzOWZ3NjFrUXF4U1RxNmtZCnJ6Y1FXM0NFZm01WDF4RXlUMFRw
            TXNLNXJ6RHE5VXFCeEZHT3VURXF2RVUKLS0tIHNFYVpVNVVSTlBCVHpNVFNxbUVN
            THBWQm1lNjV3eU5rdjh0bUFKdFhaUDgKeivgLwXPVyyF41Ax8L+irFOhr7Iriyja
            7UJu+SSlWyGO98CExa5j6i0432zhD1NzhojJU58u/sDo2WJpR7ihxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:30:29Z"
    mac: ENC[AES256_GCM,data:56G4kOxOYqapS44/fu3fWYbTSUwtmP9zQtdXi+q2iDga6wMD3dNZG7gN5cqmcvtNdwB4tEFcrBVQcJ2Sw7pRcW9+KJbBZKPXedK0LSffop8OmRYHZOpwf6pVQn14RKHOlR6yHgDH60ET/boVB4Xoh9elZXPpdSp0xGEeGWlV8sE=,iv:03NOPPlkRgZvJtdFaa/fLIZ5ujFJNCF8ROh02GcsHTs=,tag:UevuUlkzHvuOTKBPxYN2hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
