apiVersion: v1
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: mariadb-galera
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    ROOT_PASSWORD: ENC[AES256_GCM,data:yKqvRp/wfM36SIwSt9BxQ3PjZYZrpaq1kDC7lFXOMUo2G3Zdb39rKb5flcdJGokt,iv:ze6oF1xrUMt5mubD2aYVyYxyys+xYOWxbrkP3eIwdiU=,tag:qrkxAR+fjGFELLYrw2C1WA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:tfqwHzWZyJKFq2KwSt7b1FpRfsrAunpOMOgQQhrqwpw=,iv:NJjDL3JvxAomeB1L/YpgMUicZsz07ROPTa1tNMaJAE0=,tag:Zjv2GQts62g7YpDufBZBGQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rhb+mvCBpKe1Eup4uY/rneoziepsY9Ph+7UAIvUmrZ0=,iv:9e1x7tTSOB62AW5wdRbQf7H8WI7Ws8AkX695kQByQ/M=,tag:4g6O6TWVR/TYBHb4Ap4l8g==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:U/lv2iNLya4bnAXexsw0IcbrnsqAi/UbmvU=,iv:HG33JGr2mggtVpLbADPCx/hxhqKL59MBWGRQSvxV72k=,tag:GYo5Y3wFI/N9VQ8dbleVdg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOGxyOVJWZ0U3VUxhUkJj
            Znp4aXkzVENqZEhmMmFwR3I3SDExdHZsRldBCkVKMGFjZ05LMCtDWnFsUGFyUVI3
            dHFuaURJQURGeU1mdWVWVDZXZlFjM2cKLS0tIDh4SjNRc3d1K1FFcTJKdTU4MjdX
            c3JuSDVXaE9IK2Y3TjZFdFFmOXE4TXMKW/oNAvOrMUAMr6coF8OHPvmYKXdVmsSd
            JzffgrO6jlQSMTNTZvyzTHDpRKHmi2GX7D4mYqGFuL0ilrMchFDwfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T10:29:49Z"
    mac: ENC[AES256_GCM,data:A3l+cBWwUsx/lrVHATo7c+sebRf2SOQ9SazV1p/X1fm+TN7N4XAl+IH4SteyWNZvOp2slXUltFkWP7EYE8m0+kPkSBfQKkZgSxxXQ52BYljhzNvg86sdJ5CSTUi/GE5kXKL5lys2xT14e038yNskDSL0tHwWurtNRYQn69P47Zo=,iv:p4ABnRvDmPVEkFNYb9W71fnuO+SQuiEWUV4/ewtwKec=,tag:lQQ0AgpsJuc9CRC83wGNOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
