apiVersion: v1
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: databases
    labels:
        app.kubernetes.io/part-of: mariadb-galera
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    ROOT_PASSWORD: ENC[AES256_GCM,data:6z1VvBh6f0556yn+/JnGttH8Avcbvo9qNszHyZx/iZs6/4JsugZEIyYSgz01lMuR,iv:gXrbd+CAthgzbVf9XZdTT2QIUvm3bQCVLfOYAwHq9qQ=,tag:XqgJZGzjSku6w0EPvQD9XQ==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:umFP1BuscHwOhHJJf3BU/G+uesDoq/von3YLmNh3qRs=,iv:+ahOBsmKra2C41INYmShB6CDBHxxvbz9hurc/V2VRTA=,tag:/2DZc/eAb+ZsDX68cu9BEQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ApVdyHLddc07HP3+qs0d1An9tdctXlLgoCfn2vXXmU0=,iv:MtcpwFR3ZCoruEnEkkGDcEqvv2kCJ9+iPw06jPRRThw=,tag:zMFqHT8nnDqewTtjBDo1nQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:VGf4xK6JPg/Uahki89h9Qi8NnReKVypoLA==,iv:u8/xOAUZu9kminOtLg0I87VZXgh07U4WIIgErnliAbU=,tag:KI3SQ0HrThnywouv0HPVDg==,type:str]
sops:
    age:
        - recipient: age1fdqtcha9jnzqafe5t6hed6v5sv858x2tt6nwuw00u3luyxuaqcxqh5mcrm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbTBGa29qL1JjK0k1Q1Ez
            V09hMGgwa2NvempoZzJBSHVJK1RxN1pwS0YwCk15cFlUNFVtMFJMY2FzV2JxMDU5
            bnczKzhvbHczS0RwdlVIbWYrVndRcFEKLS0tIEF6RGFvcUFDV2Rpa3dqSmhGSUls
            QVJzKzFHbzVqUkJYa3R6aGJyS0hMYlEKxemZMGTFvNDqEbUkXy4QWgwM+vMGj5Ia
            SAcxLoPCHziSYC8p553IcPVpSnOL6PfzKPZY3ABvUKACsc6UbSJDVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T15:53:12Z"
    mac: ENC[AES256_GCM,data:FVVaUdcTQ6TSArqMyzNttnCPLSvTTWIzWV469KHuj57cw9j1tdCbLW+kiAv+iOrE9i4FdSmA7tdDdoI71lQZtvqqgD0nXqMu7kOvE5NWwZLSxhqzhBWiO3qeOE/eFR8jLvJaesjF+H3JZRkRIxXVM3b/154rthbMGqHfQSn37LE=,iv:owuw1wcaI8QNgV8hEe16kCTMi+6wbSqZPV9EKPLbihc=,tag:7NfCqztgSzVpWYhjhtHfLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
