---
# KSOPS Secret Generator fuer MariaDB Credentials (PROD)
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: mariadb-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./mariadb-credentials.enc.yaml
  - ./idoit-db-credentials.enc.yaml
